module.exports = {
	"SERVICE_RUNTIME_EXCEPTION":100,
	"SERVICE_BUSINESS_EXCEPTION":101,

	"TOOLCHAIN_INPUT_VALIDATION_ERR":"TOOLCHAIN_INPUT_VALIDATION_ERR",

	"GITLAB_PRJ_CRT_ERR":"GITLAB_PRJ_CRT_ERR",
	"GITLAB_GRP_CRT_ERR":"GITLAB_GRP_CRT_ERR",
	"GITLAB_PRJ_GRP_ASSN_ERR":"GITLAB_PRJ_GRP_ASSN_ERR",
	"GITLAB_USRID_USRNAME_ERR":"GITLAB_USRID_USRNAME_ERR",
	"GITLAB_USRID_GRP_ASSN_ERR":"GITLAB_USRID_GRP_ASSN_ERR",

	"JENKINS_JOB_CRT_ERR":"JENKINS_JOB_CRT_ERR",
	"JENKINS_USR_JOB_ASSN_ERR":"JENKINS_USR_JOB_ASSN_ERR",
	
	"JIRA_GROUP_CREATE_ERR":"JIRA_GROUP_CREATE_ERR",
	"JIRA_PROJECT_CREATE_ERR":"JIRA_PROJECT_CREATE_ERR",
	"JIRA_SCHEME_CREATE_ERR":"JIRA_SCHEME_CREATE_ERR",
	"JIRA_SCHEME_ASSIGN_ERR":"JIRA_SCHEME_ASSIGN_ERR",
	"JIRA_USER_ROLE_ASSIGN_ERR":"JIRA_USER_ROLE_ASSIGN_ERR",
	"ROLLBACK_ERR":"ROLLBACK_ERR",
	
	"ARTIFACTORY_PROJECT_CREATE_ERR":"ARTIFACTORY_PROJECT_CREATE_ERR",
	"ARTIFACTORY_PROJECT_DELETION_ERR":"ARTIFACTORY_PROJECT_DELETION_ERR",
	"ARTIFACTORY_PA_PERMISSION_SCHEME_CREATION_ERR":"ARTIFACTORY_PA_PERMISSION_SCHEME_CREATION_ERR",
	"ARTIFACTORY_PA_PERMISSION_SCHEME_DELETION_ERR":"ARTIFACTORY_PA_PERMISSION_SCHEME_DELETION_ERR",
	"ARTIFACTORY_GROUP_CREATION_ERR":"ARTIFACTORY_GROUP_CREATION_ERR",
	"ARTIFACTORY_GROUP_DELETION_ERR":"ARTIFACTORY_GROUP_DELETION_ERR",
	
	"SONARQUBE_PROJECT_CREATE_ERR":"SONARQUBE_PROJECT_CREATE_ERR",
	"SONARQUBE_PROJECT_DELETION_ERR":"SONARQUBE_PROJECT_DELETION_ERR",
	"SONARQUBE_GROUP_CREATION_ERR":"SONARQUBE_GROUP_CREATION_ERR",
	"SONARQUBE_GROUP_DELETION_ERR":"SONARQUBE_GROUP_DELETION_ERR",
	
	"UCD_PROJECT_CREATE_ERR":"UCD_PROJECT_CREATE_ERR",
	"UCD_TEAM_CREATE_ERR":"UCD_TEAM_CREATE_ERR",
	"UCD_TEAM_DELETION_ERR":"UCD_TEAM_DELETION_ERR",
	"UCD_GROUP_CREATE_ERR":"UCD_GROUP_CREATE_ERR",
	"UCD_GROUP_DELETION_ERR":"UCD_GROUP_DELETION_ERR",
	"UCD_ADD_GROUP_TO_TEAM_ERR":"UCD_ADD_GROUP_TO_TEAM_ERR",
	"UCD_ADD_TEAM_TO_APPLICATION_ERR":"UCD_ADD_TEAM_TO_APPLICATION_ERR",
	"UCD_ENVIRONMEMT_CREATE_ERR":"UCD_ENVIRONMEMT_CREATE_ERR",
	"UCD_ADD_TEAM_TO_ENVIRONMENT_ERR":"UCD_ADD_TEAM_TO_ENVIRONMENT_ERR",
	"UCD_ENVIRONMEMT_DELETE_ERR":"UCD_ENVIRONMEMT_DELETE_ERR",
	"UCD_COMPONENT_CREATE_ERR":"UCD_COMPONENT_CREATE_ERR",
	"UCD_ADD_COMPONENT_TO_TEAM_ERR":"UCD_ADD_COMPONENT_TO_TEAM_ERR",
	"UCD_COMPONENT_PROCESS_CREATE_ERR":"UCD_COMPONENT_PROCESS_CREATE_ERR",
	"UCD_APPLICATION_PROCESS_CREATE_ERR":"UCD_APPLICATION_PROCESS_CREATE_ERR",
	"UCD_PA_PERMISSION_SCHEME_CREATION_ERR":"ARTIFACTORY_PA_PERMISSION_SCHEME_CREATION_ERR",
	"UCD_PA_PERMISSION_SCHEME_DELETION_ERR":"ARTIFACTORY_PA_PERMISSION_SCHEME_DELETION_ERR"
};